=== scravy/Obsolete/Jazz/src/main/resources/net/abusingjava/swing/legacy/magic.dtd
<!ELEMENT magic (title?,style?,groups?,binding*,(hbox|vbox))>

<!ENTITY % box-content "hbox|vbox|flexi-space|tabs|panes|button|table|label|textfield|numeric|textarea|checkbox|combobox|select|date|datepicker|password">
<!ENTITY % bool "true|false">
<!ENTITY % event-attributes "
	onmouseover  CDATA #IMPLIED
	onmouseout   CDATA #IMPLIED
	onmousemove  CDATA #IMPLIED
	onmousewheel CDATA #IMPLIED
	onkeypress   CDATA #IMPLIED
	onkeydown    CDATA #IMPLIED
	onkeyup      CDATA #IMPLIED
	onfocus      CDATA #IMPLIED
	onblur       CDATA #IMPLIED
">
<!ENTITY % common-attributes "
	class       CDATA #IMPLIED
	name        CDATA #IMPLIED
	
	width       CDATA #IMPLIED
	height      CDATA #IMPLIED
	
	min-width   CDATA #IMPLIED
	min-height  CDATA #IMPLIED
	
	background  CDATA  #IMPLIED
	foreground  CDATA  #IMPLIED
	
	border      CDATA  #IMPLIED
	opaque      (%bool;) #IMPLIED
	
	text-align	       (left|right|center) #IMPLIED
	vertical-alignment (top|bottom|center) #IMPLIED
	font-weight        (bold|normal)       #IMPLIED
	font-style         (italic|normal)     #IMPLIED
	font-size          CDATA               #IMPLIED
	
	requires-permission CDATA #IMPLIED
	group NMTOKENS #IMPLIED
">
<!ENTITY % validator-attributes "
	validator   CDATA #IMPLIED
">
<!ENTITY % box-attributes "
	width       CDATA #IMPLIED
	height      CDATA #IMPLIED
	
	class       CDATA #IMPLIED
	name        CDATA #IMPLIED
">

<!ELEMENT style (%box-content;|class)*>
<!ELEMENT class (%box-content;)*>
<!ATTLIST class
	%common-attributes;
>

<!ELEMENT hbox (%box-content;)*>
<!ATTLIST hbox
	%box-attributes;
>
<!ELEMENT vbox (%box-content;)*>
<!ATTLIST vbox
	%box-attributes;
>

<!ELEMENT flexi-space EMPTY>
<!ATTLIST flexi-space
	%common-attributes;
>

<!ELEMENT numeric (#PCDATA)*>
<!ATTLIST numeric
	%common-attributes;
	min  CDATA #IMPLIED
	max  CDATA #IMPLIED
	step CDATA #IMPLIED
>

<!ELEMENT checkbox (#PCDATA)*>
<!ATTLIST checkbox
	%common-attributes;
>

<!ELEMENT textfield (#PCDATA)*>
<!ATTLIST textfield
	%common-attributes;
	%validator-attributes;
	%event-attributes;
>

<!ELEMENT textarea (#PCDATA)*>
<!ATTLIST textarea
	%common-attributes;
	%event-attributes;
>

<!ELEMENT date (#PCDATA)*>
<!ATTLIST date
	%common-attributes;
>
<!ELEMENT datepicker (#PCDATA)*>
<!ATTLIST datepicker
	%common-attributes;
	%event-attributes;
	onaction	CDATA	#IMPLIED
>

<!ELEMENT combobox (val*)>
<!ATTLIST combobox
	%common-attributes;
	onaction	CDATA	#IMPLIED
	sorted (%bool;) #IMPLIED
	autocomplete (%bool;) #IMPLIED
	from CDATA #IMPLIED
>
<!ELEMENT val (#PCDATA)*>
<!ATTLIST val
	selected (%bool;) #IMPLIED
>

<!ELEMENT table (col*)>
<!ATTLIST table
	%common-attributes;
	sortable (%bool;)  #IMPLIED
	grid-color CDATA   #IMPLIED
	ondblclick CDATA   #IMPLIED
>
<!ELEMENT col (#PCDATA)*>
<!ATTLIST col
	type	CDATA	#REQUIRED
	min-width CDATA #IMPLIED
	max-width CDATA #IMPLIED
>
	

<!ELEMENT label (#PCDATA)*>
<!ATTLIST label
	%common-attributes;
>

<!ELEMENT button (#PCDATA)*>
<!ATTLIST button
	%common-attributes;
	action    CDATA    #IMPLIED
	onaction    CDATA    #IMPLIED
>

<!ELEMENT password (#PCDATA)*>
<!ATTLIST password
	%common-attributes;
	onaction    CDATA    #IMPLIED
>

<!ELEMENT title (#PCDATA)*>

<!ELEMENT tabs (tab+)>
<!ELEMENT tab (title,(hbox|vbox))>
<!ATTLIST tabs
	%common-attributes;
>

<!ELEMENT panes (pane+)>
<!ATTLIST panes
	%common-attributes;
>
<!ELEMENT pane (title,(hbox|vbox))>
<!ATTLIST pane
	expanded (true|false) #IMPLIED
	animated (true|false) #IMPLIED
>

<!ELEMENT groups (group+)>
<!ELEMENT group (elem*)>
<!ATTLIST group
	name	CDATA	#REQUIRED
	requires-permission	CDATA #IMPLIED 
>
<!ELEMENT elem (#PCDATA)*>

<!ELEMENT binding (prop*)>
<!ATTLIST binding
	class	CDATA	#REQUIRED
>
<!ELEMENT prop EMPTY>
<!ATTLIST prop
	name	CDATA	#REQUIRED
	component	CDATA	#REQUIRED
>

=== scravy/Obsolete/Jazz/src/main/resources/net/abusingjava/swing/example/x1.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE magic PUBLIC "-//abusingjava.net//net.abusingjava.swing.MagicPanel//EN" "../magic.dtd">
<magic>

	<style>
		<vbox height="*" width="*" />
		<hbox height="*" width="*" />
	
		<datepicker
			height="27px" />
	
		<button
			height="27px" />
			
		<textfield
			height="27px" />
		
		<combobox
			height="27px" />
		
		<label
			height="27px" />
			
		<checkbox
			height="22px" />
		
		<table
			height="100px" min-width="200px" />
		
		<class
			name="title"
			font-weight="bold"
			height="32px"
			vertical-alignment="center" />
		
		<class
			name="leftLabel"
			width="120px" />
		
		<class
			name="phoneButton"
			width="1*" />
		
		<class
			name="phoneNumber"
			width="3*" />
			
		<class
			name="eMailAddress"
			width="4*" />
			
		<class
			name="eMailAddressMargin"
			width="3*" />
		
		<class
			name="vMargin"
			height="5px" />
		
		<class
			name="hMargin"
			width="10px"
			height="*" />
		
		<class
			name="autoHeight"
			height="auto" />
			
		<class
			name="freeSpace" />
	</style>

	<vbox>
		<hbox height="autoHeight">
			<flexi-space class="hMargin" />
			<label font-size="20px" height="40px">Bürger Lars Dietrich, Kd.Nr. #234798</label>
		</hbox>
		
		<hbox>
			<flexi-space class="hMargin" />
			<!-- LINKE SEITE -->
			<vbox width="450px">
				<vbox class="autoHeight">
			
				<table height="200px" name="tabelle">
					<col max-width="30" type="java.lang.Boolean">?</col>
					<col type="string">StriNG</col>
				</table>
			
				<button name="just" onaction="doIt">JUSTdoIT</button>
			
				<label class="title">Persönliche Bewerberdaten</label>
				<hbox>
					<label class="leftLabel">Name, Vorname</label>
					<textfield name="nachname" validator="dfv.klient.validators.TextFieldValidator"></textfield>
					<textfield name="vorname"></textfield>
					<combobox width="60px" from="net.abusingjava.swing.example.Gender" />
				</hbox>
				<hbox>
					<label class="leftLabel">Straße</label>
					<textfield></textfield>
				</hbox>
				<hbox>
					<label class="leftLabel">PLZ, Ort, Land</label>
					<textfield width="70px" validator="net.abusingjava.swing.example.PLZValidator"></textfield>
					<textfield width="1*"></textfield>
					<combobox width="1*" sorted="true" from="net.abusingjava.swing.example.Nations">
						<val>Lichtenstein</val>
						<val>Schweiz</val>
						<val selected="true">Deutschland</val>
						<val>Finnland</val>
						<val>Norwegen</val>
						<val>Russland</val>
						<val>Weißrussland</val>
						<val>Lettland</val>
						<val>Estland</val>
						<val>Litauen</val>
						<val>Schweden</val>
						<val>Vereinigtes Königreich</val>
						<val>Italien</val>
						<val>Österreich</val>
						<val>Tschechien</val>
						<val>Slowenien</val>
						<val>Slowakei</val>
						<val>Andorra</val>
						<val>Spanien</val>
						<val>Kroatien</val>
						<val>Albanien</val>
						<val>Zypern</val>
						<val>Mazedonien</val>
						<val>Türkei</val>
						<val>Bulgarien</val>
						<val>Ungarn</val>
						<val>Ukraine</val>
						<val>Kasachstan</val>
						<val>China</val>
						<val>Indien</val>
						<val>Ägypten</val>
						<val>Vereinigte Staaten</val>
						<val>Mexiko</val>
						<val>Kanada</val>
						<val>Irland</val>
						<val>Dänemark</val>
						<val>Island</val>
						<val>Polen</val>
					</combobox>
				</hbox>
				<hbox>
					<label class="leftLabel">Geburtsdatum</label>
					<datepicker width="4*" />
					<label width="3*" text-align="center">23 Jahre alt</label>
				</hbox>
				<flexi-space class="vMargin" />
				<label class="title">Kontaktdaten</label>
				<hbox>
					<button action="net.abusingjava.swing.example.ButtonAction" class="phoneButton">T1</button>
					<textfield class="phoneNumber"></textfield>
					<button class="phoneButton">T2</button>
					<textfield class="phoneNumber"></textfield>
				</hbox>
				<hbox>
					<button class="phoneButton">H1</button>
					<textfield class="phoneNumber"></textfield>
					<button class="phoneButton">H2</button>
					<textfield class="phoneNumber"></textfield>
				</hbox>
				<hbox>
					<button class="phoneButton">Fax1</button>
					<textfield class="phoneNumber"></textfield>
					<button class="phoneButton">Fax2</button>
					<textfield class="phoneNumber"></textfield>
				</hbox>
				<flexi-space class="vMargin" />
				<hbox>
					<button class="phoneButton">Mail</button>
					<textfield class="eMailAddress"></textfield>
					<flexi-space class="eMailAddressMargin" />
				</hbox>
				<hbox>
					<button class="phoneButton">Mail</button>
					<textfield class="eMailAddress"></textfield>
					<flexi-space class="eMailAddressMargin" />
				</hbox>
				<flexi-space class="vMargin" />
				
				<label class="title">Profil</label>
				<hbox>
					
				</hbox>
				
				</vbox>
				<flexi-space class="freeSpace" />
			</vbox>
			
			<flexi-space class="hMargin" />
			
			<flexi-space background="gray" width="1px" />
			
			<!-- RECHTE SEITE -->
			<flexi-space class="hMargin" />
			<vbox>
				<vbox class="autoHeight">
			
				<label class="title">DFV</label>
				<hbox>
					<label>Vertrag</label>
					<combobox width="2*">
						<val>-</val>
						<val>1. Rate</val>
						<val>2. Rate</val>
						<val>SZ</val>
					</combobox>
					<flexi-space />
					<label>Gültig bis</label>
					<datepicker width="2*" />
					<flexi-space />
				</hbox>
				
				<flexi-space class="vMargin" />
				<label class="title">Eingereichte Unterlagen</label>
				<hbox>
					<vbox>
						<checkbox name="lebenslauf">Lebenslauf</checkbox>
						<checkbox>Personalbogen</checkbox>
						<checkbox>Arbeitszeugnis</checkbox>
					</vbox>
					<vbox>
						<checkbox>Gültiger W.</checkbox>
						<checkbox>Qualif. Nachweis</checkbox>
						<checkbox>Gültiger VGS</checkbox>
					</vbox>
					<vbox>
						<checkbox>Ticket</checkbox>
						<checkbox>Nochmal</checkbox>
						<checkbox>OK</checkbox>
					</vbox>
				</hbox>
				
				<flexi-space class="vMargin" />
				<hbox>
					<vbox>
						<label class="title">Bewerbungskommentar</label>
						<textarea height="200px">Maecenas faucibus mollis interdum. Curabitur blandit tempus porttitor. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus. Duis mollis, est non commodo luctus, nisi erat porttitor ligula, eget lacinia odio sem nec elit. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Nullam id dolor id nibh ultricies vehicula ut id elit.
	
	Etiam porta sem malesuada magna mollis euismod. Nulla vitae elit libero, a pharetra augue. Cras mattis consectetur purus sit amet fermentum. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.
	
	Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus sagittis lacus vel augue laoreet rutrum faucibus dolor auctor. Vivamus sagittis lacus vel augue laoreet rutrum faucibus dolor auctor. Duis mollis, est non commodo luctus, nisi erat porttitor ligula, eget lacinia odio sem nec elit. Aenean eu leo quam. Pellentesque ornare sem lacinia quam venenatis vestibulum. Donec sed odio dui. Integer posuere erat a ante venenatis dapibus posuere velit aliquet.
	
	Donec ullamcorper nulla non metus auctor fringilla. Cras justo odio, dapibus ac facilisis in, egestas eget quam. Nulla vitae elit libero, a pharetra augue. Morbi leo risus, porta ac consectetur ac, vestibulum at eros. Curabitur blandit tempus porttitor. Maecenas faucibus mollis interdum.</textarea>
				
					</vbox>
					<vbox>
						<label class="title">Tätigkeiten</label>
						<textarea height="200px"></textarea>
					</vbox>
				</hbox>
				<hbox>
					<vbox>
						<label class="title">Berufe</label>
						<table sortable="true">
							<col type="String">Beruf</col>
							<col type="Date">Von</col>
							<col type="Date">Bis</col>
						</table>
					</vbox>
					<vbox>
						<label class="title">Ausbildungen</label>
						<table>
							<col type="String">Ausbildung</col>
							<col type="Date">Von</col>
							<col type="Date">Bis</col>
						</table>
					</vbox>
				</hbox>
				
				<flexi-space class="vMargin" />
				
				<flexi-space background="red" />
				
				</vbox>
				<flexi-space class="freeSpace" />
			</vbox>
			
			<flexi-space class="hMargin" />
		</hbox>
	</vbox>


</magic>

=== scravy/Obsolete/Jazz/src/main/resources/net/abusingjava/swing/example/x2.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE magic PUBLIC "-//abusingjava.net//net.abusingjava.swing.MagicPanel//EN" "../magic.dtd">
<magic>

	<style>
		<vbox height="*" width="*" />
		<hbox height="*" width="*" />
	
		<datepicker
			height="27px" />
	
		<password height="27px" />
	
		<button
			height="27px" />
			
		<textfield
			height="27px" />
		
		<combobox
			height="27px" />
		
		<label
			height="27px" />
			
		<checkbox
			height="22px" />
		
		<table
			height="100px" min-width="200px" />
		
		<class
			name="title"
			font-weight="bold"
			height="32px"
			vertical-alignment="center" />
		
		<class
			name="leftLabel"
			width="120px" />
		
		<class
			name="phoneButton"
			width="1*" />
		
		<class
			name="phoneNumber"
			width="3*" />
			
		<class
			name="eMailAddress"
			width="4*" />
			
		<class
			name="eMailAddressMargin"
			width="3*" />
		
		<class
			name="vMargin"
			height="5px" />
		
		<class
			name="hMargin"
			width="10px"
			height="*" />
		
		<class
			name="autoHeight"
			height="auto" />
			
		<class
			name="freeSpace" />
	</style>

	<hbox>
		<vbox>
			<flexi-space />
			<combobox autocomplete="true">
				<val>Frankreich</val>
				<val>Franz√§sisch Guinea</val>
			</combobox>
			<flexi-space />
		</vbox>
		<vbox>
			<panes height="*" width="*">
				<pane>
					<title>THis is a title</title>
					<vbox>
						<hbox>
							<button>Thingies</button>
							<button>Thingies</button>
						</hbox>
						<button>Thingie</button>
					</vbox>
				</pane>
				<pane>
					<title>THis is a title</title>
					<vbox>
						<hbox>
							<button>Thingies</button>
							<button>Thingies</button>
						</hbox>
						<button>Thingie</button>
					</vbox>
				</pane>
				<pane expanded="true">
					<title>THis is a title</title>
					<vbox>
						<hbox>
							<button>Thingies</button>
							<button>Thingies</button>
						</hbox>
						<button>Thingie</button>
					</vbox>
				</pane>
				<pane>
					<title>THis is a title</title>
					<vbox>
						<hbox>
							<button>Thingies</button>
							<button>Thingies</button>
						</hbox>
						<button>Thingie</button>
					</vbox>
				</pane>
			</panes>
		</vbox>
	</hbox>
	
</magic>

=== scravy/Obsolete/Jazz/src/main/resources/net/abusingjava/swing/example/sample4.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE magic PUBLIC "-//abusingjava.net//net.abusingjava.swing.MagicPanel//EN" "../magic.dtd">
<magic>

	<style>
		<label text-align="center" />
		<textfield height="27px" />
		<checkbox height="25px" />
	</style>

	<hbox>
		<vbox width="150px">
			<label height="50px">top-left</label>
			<button>left</button>
			<label height="50px" text-align="left">bottom-left</label>
		</vbox>
		<vbox>
			<label height="50px">top</label>
			<hbox>
				<flexi-space />
					<vbox width="300px">
						<flexi-space />
						<textfield>1</textfield>
						<textfield>2</textfield>
						<textfield>3</textfield>
						<flexi-space height="27px" />
						<hbox height="27px">
							<flexi-space />
							<button background="0x009900" foreground="white" width="100px" height="27px">OK</button>
							<button background="0x990000" foreground="white" width="100px" height="27px">Abbruch</button>
						</hbox>
						<flexi-space />
					</vbox>
				<flexi-space />
			</hbox>
			<label height="50px">bottom</label>
		</vbox>
		<vbox width="200px">
			<label height="50px">top-right</label>
			<vbox>
				<checkbox>Option 1</checkbox>
				<checkbox>Option 2</checkbox>
				<checkbox>Option 3</checkbox>
				<flexi-space />
			</vbox>
			<label height="50px">bottom-right</label>
		</vbox>
	</hbox>

</magic>

=== scravy/Obsolete/Jazz/src/main/resources/net/abusingjava/swing/example/sample-colourful-buttons.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE magic SYSTEM "../magic.dtd">
<magic>

	<style>
		<button height="27px" />
	</style>

	<hbox>
		<vbox>
			<flexi-space />
		</vbox>
	
		<vbox width="200px">
			<flexi-space />
			<button background="0x000000" />
			<button background="0xFFFFFF" />
			<button background="0xCC00CC" />
			<button background="0xCC0000" />
			<button background="0x0099FF" />
			<button background="0x33CC33" />
			<button background="0xFF9900" />
			<button background="0xFFCC00" />
			<button background="0x663399" />
			<button background="0x3333CC" />
			<flexi-space />
		</vbox>

		<vbox>
			<flexi-space />
		</vbox>
	</hbox>

</magic>

=== scravy/Obsolete/Jazz/src/main/resources/net/abusingjava/swing/example/sample-colourful-boxes.xml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE magic SYSTEM "../magic.dtd">
<magic>

	<style>
		
	</style>
	
	<hbox>
		<vbox>
			<flexi-space background="red" />
			<flexi-space background="blue" />
		</vbox>
		<vbox>
			<flexi-space background="green" />
			<flexi-space background="yellow" />
		</vbox>
	</hbox>
	
</magic>
